version: '3.3'

services:
  data-api:
    build: data-api
    network_mode: "host"  
    volumes: 
      - '~/.aws/:/home/ec2-user/.aws/'
      - '/opt/:/opt/'
      - '/run/:/run/'
      - '/home/slurm/:/home/slurm/'
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    restart: always
