version: '3.3'

services:
  data-api:
    build: data-api
    ports:
      - "80:5010"
      - "5500:5500"
      - "5510:5510"
    volumes: 
      - './data/:/data/'
      - '~/.aws/:/.aws/'
    restart: always
  ingest:
    build: ingest
    ports:
      - "8787:8787"
    volumes: 
      - './data/:/data/'
      - '~/.aws/:/.aws/'
    restart: always
