version: '3.3'

services:
  data-api:
    build: data-api
    ports:
      - "80:5010"
      - "8787:8787"
    volumes: 
      - '~/data/:/data/'
      - '~/.aws/:/home/ec2-user/.aws/'
      - '/opt/:/opt/'
      - '/var/:/var/'
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    restart: always
