server:
    bind:
        host: 0.0.0.0
        port: 5010
    url: http://ec2-44-228-159-61.us-west-2.compute.amazonaws.com:5010/
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    language: en-US
    cors: true
    pretty_print: true
    limit: 10
    # templates: /path/to/template

logging:
    level: DEBUG
    logfile: /data/edr.log


groups:
    US_Models:
        type: group
        name: United States Models
        desc: Automated Ingestion
        children: 
            - automated_gfs
            - ndfd_xml
    Environment_Canada_Models:
        type: group
        name: Environment Canada Models
        desc: Automated Ingestion
        children:
            - automated_gem
    NWS:
        type: group
        name: NWS
        desc: National Weather Service models
        children:
            - gfs
    OBSERVATIONS:
        type: group
        name: OBSERVATIONS
        desc: Observation data
        children:
            - metar
            - metar_tgftp
    Annex_3_Forecast_Product:
        type: group
        name: Aviation Forecast Product
        desc: aviation forecast product
        children:
            - taf
            - tca
            - vaa
            - WIFS
    NASA:
        type: group
        name: NASA data from HDF5 ingest
        desc: NASA precipitation analysis
        children:
            - automated_nasa
    global:
        type: group
        name: Global
        desc: Global models
        children:
            - gfs
metadata:
    
    registry_db: EDR/WMO.sqlite
    identification:
        title: Environmental Data Retrieval API
        description: National Weather Service Instance of the EDR-API
        keywords:
            - point
            - polygon
            - environmental
            - data
            - api
        keywords_type: theme
        terms_of_service: None
        url: weather.gov
    license:
#        name: CC-BY 4.0 license
#        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: National Weather Service
        url: https://weather.gov
    contact:
        name: Shane Mill
        position: Application Developer
        address: 
        city: 
        state: 
        postalcode:
        country: United States
        phone: 
        fax: 
        email: shane.mill@noaa.gov
        url: 
        hours: 
        instructions: 
        role: pointOfContact

datasets:
    # underscores are not allowed in dataset identifiers
    automated_gfs:
        name: gfs automated
        title: gfs automated
        description: gfs automated
        extent:
            spatial: 0.0,-90.0,359.9,90.0
        instanceAxes:
            x:
                label: Longitude
                lowerBound: 0.0
                upperBound: 359.9
                uomLabel: degrees
            y:
                label: Latitude
                lowerBound: -90.0
                upperBound: 90.0
                uomLabel: degrees
        provider:
            name: automated_provider
            type: automated_ingest
            output_formats: ['CoverageJSON','GRIB','NetCDF','COGeotiff']
            model: [gfs_100]
            cycle: [00z]
            data_source: 's3://enviroapi-bucket-1/zarr'
    national_water_model:
        name: national_water_model
        title: National Water Model Reanalysis
        description: National Water Model Reanalysis
        extent:
            spatial: 0.0,-90.0,359.9,90.0
        instanceAxes:
            x:
                label: Longitude
                lowerBound: 0.0
                upperBound: 359.9
                uomLabel: degrees
            y:
                label: Latitude
                lowerBound: -90.0
                upperBound: 90.0
                uomLabel: degrees
        provider:
            name: s3_zarr
            type: s3_zarr
            output_formats: ['CoverageJSON','NetCDF']
            data_source: 's3://noaa-nwm-retro-v2-zarr-pds/'
            output_location: '/home/ec2-user/data/collections' 
            meta: './nwm_times.csv'
    wifs_png:
        name: wifs_png
        title: WIFS Significant Weather Charts
        description: WIFS Significant Weather Charts
        provider:
            name: wifs_png
            type: wifs_png
            cycle: ['0000','0600','1200','1800']
            output_formats: ['png']
            data_source: https://aviationweather.gov/wifs/data/PNG/SIGWX/KWBC/
    metar:
        name: metar
        title: Metar observations
        description: Last 36 Hours of Global Metar observations
        extent: 
            spatial: -180.0,-89.9,180.0,89.9
        instanceAxes:
            x:
                label: Longitude
                lowerBound: -180
                upperBound: 180
                uomLabel: degrees
            y:
                label: Latitude
                lowerBound: -89.9
                upperBound: 89.9
                uomLabel: degrees
            attributes:
                wkt: GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.01745329251994328,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]]
                proj4: +proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs            
        parameters:
            air_temperature: 
                - /metadata/bufr4/d/307045-012023
                - 1.5
                - temp
                - int
            dewpoint_temperature: 
                - /metadata/bufr4/d/307045-012024
                - 1.5
                - dewpt
                - int
            wind_speed: 
                - /metadata/bufr4/d/307045-011002
                - 10.0
                - wind_speed
                - int
            wind-gust: 
                - /metadata/bufr4/d/307045-011041
                - 10.0
                - wind_gust
                - int
            wind_from_direction: 
                - /metadata/bufr4/d/307045-011001
                - 10.0
                - wind_dir
                - int
            visibility: 
                - /metadata/bufr4/d/307051-307046
                - 10.0
                - vis
                - int
            pressure: 
                - /metadata/bufr4/d/302031-007004
                - None
                - press
                - int
            msl_pressure: 
                - /metadata/bufr4/d/302051-010051
                - None
                - mslp
                - int
            raw_ob: 
                - {"type": "Parameter","description": {"en": "raw ob"},"unit": {"label": {"en": ""},"symbol": {"value": "","type": "https://www.wmo.int/pages/prog/www/WMOCodes/WMO306_vI1/Publications/2014update/306_vol_I1_2014_en_track.pdf"}},"observedProperty": {"id": "Raw Metar Observation","label": {"en": "Raw Metar Observation"}}}
                - None
                - raw_ob
                - str
            icao_id: 
                - {"type": "Parameter","description": {"en": "icao id"},"unit": {"label": {"en": ""},"symbol": {"value": "","type": "https://en.wikipedia.org/wiki/ICAO_airport_code"}},"observedProperty": {"id": "ICAO id","label": {"en": "ICAO id"}}}
                - None
                - icao_id
                - str
        provider:
            name: metar
            type: obs
            output_formats: ['CoverageJSON','xml']
            data_source: https://www.aviationweather.gov/metar/data
            station_list_db: EDR/stations.sqlite 
    taf:
        name: taf
        title: Terminal Aerodrome Forecasts
        description: Latest Forecasts
        extent:
            spatial: -180.0,-89.9,180.0,89.9
        instanceAxes:
            x:
                label: Longitude
                lowerBound: -180
                upperBound: 180
                uomLabel: degrees
            y:
                label: Latitude
                lowerBound: -89.9
                upperBound: 89.9
                uomLabel: degrees
            attributes:
                wkt: GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.01745329251994328,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]]
                proj4: +proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs
        parameters:
            wind_speed:
                - /metadata/bufr4/d/307045-011002
                - 10.0
                - wind_speed
                - int
            wind-gust:
                - /metadata/bufr4/d/307045-011041
                - 10.0
                - wind_gust
                - int
            wind_from_direction:
                - /metadata/bufr4/d/307045-011001
                - 10.0
                - wind_dir
                - int
            visibility:
                - /metadata/bufr4/d/307051-307046
                - 10.0
                - vis
                - int
            sky:
                - /metadata/bufr4/d/302031-007004
                - None
                - sky
                - str
            weather:
                - /metadata/bufr4/d/302051-010051
                - None
                - None
                - str
            raw_fcst:
                - {"type": "Parameter","description": {"en": "raw ob"},"unit": {"label": {"en": ""},"symbol": {"value": "","type": "https://www.wmo.int/pages/prog/www/WMOCodes/WMO306_vI1/Publications/2014update/306_vol_I1_2014_en_track.pdf"}},"observedProperty": {"id": "Terminal Aerodrome Forecasts","label": {"en": "Terminal Aerodrome Forecasts"}}}
                - None
                - raw_ob
                - str
            icao_id:
                - {"type": "Parameter","description": {"en": "icao id"},"unit": {"label": {"en": ""},"symbol": {"value": "","type": "https://en.wikipedia.org/wiki/ICAO_airport_code"}},"observedProperty": {"id": "ICAO id","label": {"en": "ICAO id"}}}
                - None
                - icao_id
                - str

        provider:
            name: taf
            type: obs
            output_formats: ['json','xml','tac']
            data_source: https://aviationweather.gov/taf/data
            station_list_db: EDR/stations.sqlite
    metar_tgftp:
        name: metar_tgftp
        title: METAR from the tgftp website
        description: Latest Observations
        extent:
            spatial: placeholder
        instanceAxes:
            x:
                label: Longitude
                lowerBound: -180
                upperBound: 180
                uomLabel: degrees
            y:
                label: Latitude
                lowerBound: -89.9
                upperBound: 89.9
                uomLabel: degrees
            attributes:
                wkt: GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.01745329251994328,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]]
                proj4: +proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs
        parameters:
            all:
               - all
        provider:
            name: metar_tgftp
            type: tgftp
            cycle: ['latest','00Z','01Z','02Z','03Z','04Z','05Z','06Z','07Z','08Z','09Z','10Z','11Z','12Z','13Z','14Z','15Z','16Z','17Z','18Z','19Z','20Z','21Z','22Z','23Z','24Z']
            data_representation: ['raw','decoded']
            output_formats: ['ascii','xml','json']
            data_source: https://tgftp.nws.noaa.gov/data/observations/metar/
            t1t2_data_source: https://tgftp.nws.noaa.gov/data/raw/sa/
    
    wwa_active:
        name: wwa_active
        title: Active Watches, Warnings, and Advisories
        description: Active Watches, Warnings, and Advisories
        provider:
            name: wwa_active
            data_source: https://alerts.weather.gov/cap/us.php?x=1
            output_formats: ['cap','json']
    gfs:
        name: gfs_025
        title: Global Forecast System (GFS) 
        description: Global Forecast System (GFS) Model Global 0.25 degree Data
        extent: 
            spatial: -180,-90,180,90
        instanceAxes:
            x:
                label: Longitude
                lowerBound: -180.0
                upperBound: 180.0
                uomLabel: degrees
            y:
                label: Latitude
                lowerBound: -89.9
                upperBound: 89.9
                uomLabel: degrees
            z:
                label: 
                lowerBound: 
                upperBound: 
                uomLabel: 
            t:
                label: Time
                lowerBound: 
                upperBound: 
                uomLabel: ISO8601
            attributes:
                wkt: GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.01745329251994328,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]]
                proj4: +proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs 

        parameters:
        provider:
            name: thredds
            type: thredds
            output_formats: ['CoverageJSON']
            data_source: http://thredds.ucar.edu/thredds/catalog.xml            
            proj4: +proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs
            sub_detail: GFS Quarter Degree Forecast
            datasets: Latest Collection for GFS Quarter Degree Forecast

